options:
  dcf_path: "@BUS_CONFIG_PATH@"
  # dcf_path: install/dryve_tests/share/dryve_tests/config/aaa

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000
  namespace: "/"

nodes:
  dryve-d1:
    node_id: 2
    driver: "ros2_canopen::Cia402Driver"
    package: "canopen_402_driver"
    dcf: "20231116-dryve-D1-4PDO.eds"
    namespace: "/dryve"


