
options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 100000  # In us: 1000000 = 1000ms = 1Hz SYNC

defaults:
  # dcf: "cia402_slave.eds"
  dcf: "20231116-dryve-D1-4PDO.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  diagnostics:
    enable: true
    period: 1000 # in milliseconds
  polling: true
  heartbeat_producer: 100 # Heartbeat every 1000 ms
  boot_timeout_ms: 100
  # product_code: 1001

  # Cia402Driver specific
  period: 100 # Refresh period for 402 state machine. Should be similar to sync period of master.
  # position_mode: 1 # The drives operation mode to use for the position interface
  # velocity_mode: 3 # The drives operation mode to use for the velocity interface
  # switching_state: 3 #The state to switch the operation mode in.
  
  sdo:  # Executed during configuration
    - {index: 0x6040, sub_index: 0, value: 6}           # Dryve state machine: Shutdown
    - {index: 0x6040, sub_index: 0, value: 7}           # Dryve state machine: Switch on
    - {index: 0x6040, sub_index: 0, value: 0xF}         # Dryve state machine: Enable Operation
    # - {index: 0x6060, sub_index: 0, value: 3}           # Switch to velocity mode
    # - {index: 0x6083, sub_index: 0, value: 0x6400}         # Set max acceleration to 25600
    # - {index: 0x6084, sub_index: 0, value: 0x6400}         # Set max decceleration to 25600

# Specify CANOpen NodeIDs
nodes:
  dryve:
    node_id: 2

    # - {index: 0x60FF, sub_index: 0, value: 0xA00}         # Set target speed
  #
  # tpdo:
  #   1:
  #     enabled: true
  #     cob_id: "auto"
  #     transmission: 0x01  # synchronous (on SYNC)
  #     mapping:
  #       - {index: 0x6041, sub_index: 0}  # Statusword
  #       - {index: 0x6061, sub_index: 0}  # Mode of operation display
  #   2:
  #     enabled: true
  #     cob_id: "auto"
  #     transmission: 0x01
  #     mapping:
  #       - {index: 0x6064, sub_index: 0}  # Position actual value
  #       - {index: 0x606C, sub_index: 0}  # Velocity actual value
  #   3:
  #     enabled: false
  #   4:
  #     enabled: false
  #
  # rpdo:
  #   1:
  #     enabled: true
  #     cob_id: "auto"
  #     mapping:
  #       - {index: 0x6040, sub_index: 0}  # Controlword
  #       - {index: 0x6060, sub_index: 0}  # Mode of operation (can be omitted if already in SDO)
  #   2:
  #     enabled: true
  #     cob_id: "auto"
  #     mapping:
  #       - {index: 0x607A, sub_index: 0}  # Target position (not required in velocity mode but often mapped)
  #       - {index: 0x60FF, sub_index: 0}  # Target velocity
  #   3:
  #     enabled: false
  #   4:
  #     enabled: false
  #
